// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp4QCvZTrkzpQAgTBV_Shd6BIw1Q0B0D4',
    appId: '1:327467783397:web:a99ce96ac34f05118a300c',
    messagingSenderId: '327467783397',
    projectId: 'bilin-zayy-c6d36',
    authDomain: 'bilin-zayy-c6d36.firebaseapp.com',
    storageBucket: 'bilin-zayy-c6d36.appspot.com',
    measurementId: 'G-WJVQ3ZD141',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJMD_5b_EhE78JT33ilPvjqwPVLumaii0',
    appId: '1:327467783397:android:a5ec72df925502198a300c',
    messagingSenderId: '327467783397',
    projectId: 'bilin-zayy-c6d36',
    storageBucket: 'bilin-zayy-c6d36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu53FhvZTNdnA6xLBPUKULMY4CcXx36sc',
    appId: '1:327467783397:ios:e81f2eac682747078a300c',
    messagingSenderId: '327467783397',
    projectId: 'bilin-zayy-c6d36',
    storageBucket: 'bilin-zayy-c6d36.appspot.com',
    androidClientId: '327467783397-957cropld0rpfk901ujh86of0icnfh47.apps.googleusercontent.com',
    iosClientId: '327467783397-m76nk0i860rj3sgtjtdd4pct5i5gsdo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.belinZayyAdmin',
  );
}
